### ISSUE TITLE
Problen in android studio 3.0 beta 2 and support library 26.0.1

### ISSUE THREAD

**Issue by m7mdyahia** [consp1racy/android-support-preference#76] opened 2017-08-24 12:23 UTC
adding this library as dependency causes the Android studio layout preview not to work

**Comment by consp1racy** [comment] 2017-08-24 19:35
Do you mean preview of preference XML or preview of layout XML?

Did it work in Android Studio 2 and support library 25?
Does it work in Android Studio 3 and support library 25?
Does it work in Android Studio 2 and support library 26?

Which of these combinations starts to cause errors?

**Comment by m7mdyahia** [comment] 2017-09-01 11:37
all the support components are not previewd

1-Android Studio 3 (canary 1,2,3 beta 1,2)
2-New Project -> navigation activity
3-app build.gradle


apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    buildToolsVersion "26.0.1"
    defaultConfig {
        applicationId "com.example.mohammad.testformaterialpreference"
        minSdkVersion 19
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.0.1'
    implementation 'com.android.support:design:26.0.1'
    compile "com.android.support:preference-v7:26.0.1"
    implementation 'net.xpece.android:support-preference:1.2.7'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
}
4-add styles
5-open layout editor 

The following classes could not be instantiated:
- android.support.design.widget.CoordinatorLayout (Open Class, Show Exception, Clear Cache)
- android.support.v7.widget.AppCompatTextView (Open Class, Show Exception, Clear Cache)

Exception Details java.lang.NoSuchFieldError: CoordinatorLayout   at android.support.design.widget.CoordinatorLayout.<init>(CoordinatorLayout.java:208)   at android.support.design.widget.CoordinatorLayout.<init>(CoordinatorLayout.java:200)   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)   at android.view.LayoutInflater.inflate(LayoutInflater.java:492)   at android.view.LayoutInflater.inflate(LayoutInflater.java:394)

**Comment by m7mdyahia** [comment] 2017-09-06 14:38
I think this is something related t dependency resolution.
Did api26 branch solve this?

**Comment by consp1racy** [comment] 2017-09-07 08:04
@m7mdyahia Can you confirm this is still an issue in Android Studio 3.0.0-beta4 and support library 26.0.2?

> I think this is something related t dependency resolution.

As long as you explicitly specify the `preference-v7` version correctly, there's no conflict.

Here's what I did:

1) New Project, no Kotlin, API 19-26, Bottom Navigation Activity
2) Add dependencies like so:

```
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.0.2'
    implementation 'com.android.support:design:26.0.2'
    implementation 'com.android.support:support-vector-drawable:26.0.2'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation('com.android.support.test.espresso:espresso-core:3.0.1', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })

    implementation "com.android.support:preference-v7:26.0.2"
    implementation 'net.xpece.android:support-preference:1.2.7'
}
```

3) It's still working.

![image](https://user-images.githubusercontent.com/4589773/30152298-f7b99f20-93b2-11e7-9f80-915196ab5a61.png)

It's hard for me to believe that the issue is this library's fault, because it transitively depends on other libraries and if there were any conflicting classes the project wouldn't compile at all. In other words there's no way this library can change behavior of any support library.

Android Studio layout preview is known to have had issues over the years. It looks like this issue is being tracked here: https://issuetracker.google.com/issues/64464228

**Comment by m7mdyahia** [comment] 2017-09-07 09:52
Thanks for your reply 😄 

the problem is with coordinator layout not constraint-layout, the constraint layout is un-bundled library and doesn't belong to the support library dependencies

So the problem still exists with Android Studio 3.0.0-beta4 just when adding this library dependency

**Comment by m7mdyahia** [comment] 2017-10-15 15:08
the issue is gone now with version 1.3.1
thanks

**Comment by consp1racy** [comment] 2017-10-15 17:46
I'm glad it's working, but it must be a coincidence. Layout preview got better for me in Android Studio 3.0.0-beta7, have you updated as well?

Will close the issue for now.

**Closed as completed by consp1racy** 2017-10-15 17:46 UTC

**Comment by m7mdyahia** [comment] 2017-10-15 17:58
yes I updated to RC1
