### ISSUE TITLE
java.lang.ClassCastException: android.support.v4.widget.NestedScrollView cannot be cast to android.widget.ScrollView

### ISSUE THREAD

**Issue by shmoula** [consp1racy/android-support-preference#9] opened 2015-12-06 19:12 UTC
I just received exception through Mint. It happened on samsung Galaxy Nexus running Android 4.1.1. Stack trace is as follows:

`0  java.lang.RuntimeException: Unable to start activity ComponentInfo{cz.shmoula.nxtwalch/net.xpece.android.support.app.RingtonePickerActivity}: java.lang.ClassCastException: android.support.v4.widget.NestedScrollView cannot be cast to android.widget.ScrollView
1   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2074)
2   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2099)
3   at android.app.ActivityThread.access$600(ActivityThread.java:145)
4   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
5   at android.os.Handler.dispatchMessage(Handler.java:119)
6   at android.os.Looper.loop(Looper.java:137)
7   at android.app.ActivityThread.main(ActivityThread.java:4873)
8   at java.lang.reflect.Method.invokeNative(Native Method)
9   at java.lang.reflect.Method.invoke(Method.java:528)
10  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
11  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
12  at dalvik.system.NativeStart.main(Native Method)
13  Caused by: java.lang.ClassCastException: android.support.v4.widget.NestedScrollView cannot be cast to android.widget.ScrollView
14  at net.xpece.android.support.app.AlertController.setupContent(AlertController.java:545)
15  at net.xpece.android.support.app.AlertController.setupView(AlertController.java:431)
16  at net.xpece.android.support.app.AlertController.installContent(AlertController.java:240)
17  at net.xpece.android.support.app.AlertActivity.setupAlert(AlertActivity.java:90)
18  at net.xpece.android.support.app.RingtonePickerActivity.onCreate(RingtonePickerActivity.java:188)`

**Comment by consp1racy** [comment] 2015-12-08 00:01
Caused by incompatibility of code ported from AOSP with new appcompat-v7 internals. Fixed in new release.

Beware, the new version 0.5.0 uses preference-v7 as its base instead of native preference which will require you to change some things on your end (mostly just using XpPreferenceFragment instead of AppCompatPreferenceActivity).

**Closed as completed by consp1racy** 2015-12-08 00:01 UTC
Labels: bug
